### ISSUE TITLE
can't run on other systems

### ISSUE THREAD

**Issue by runPEx0** [Nick-Vinesmoke/The-Murk-stealer#1]
can't run the built file on other systems unless they have tons of random python modules installed..

**Comment by Nick-Vinesmoke** [comment]
What OS do you use?

**Comment by Nick-Vinesmoke** [comment]
TheMurkBuilder.exe schuld open on every os

**Comment by runPEx0** [comment]
I'm talking about the builded payload afterwards. It gets errors on any other machine about python modules not being installed.
