### ISSUE TITLE
again

### ISSUE THREAD

**Issue by Hoangdepzaivcl** [Nick-Vinesmoke/The-Murk-stealer#102]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/124053344/8d9e6bea-12f0-4244-85af-747e97ac109c)

**Comment by Nick-Vinesmoke** [comment]
I gonna fix it

**Comment by Nick-Vinesmoke** [comment]
use it
https://github.com/Nick-Vinesmoke/The-Murk-stealer/issues/96
