### ISSUE TITLE
Error with compiler

### ISSUE THREAD

**Issue by l3qso** [Nick-Vinesmoke/The-Murk-stealer#106]
it said this while building rat

![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/129872317/e36f097d-13e4-4a20-ad42-99935c89012d)

any solutions? i'd be pleased

**Comment by l3qso** [comment]
it still created rat but when i ran it for a test it said this 
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/129872317/3087c9f0-efe0-46cf-8a29-5e634beba196)

**Comment by l3qso** [comment]
when i retry building it said The system cannot find the file specified

**Comment by Nick-Vinesmoke** [comment]
try to use another building method

**Comment by Nick-Vinesmoke** [comment]
**Meet the new version v9.3.0 of The Murk**
_🔐Powerful multi-platform stealer with a huge pack of grabbed data. Wallets stealer, browsers stealer, sessions stealer, etc. All logs will be sent using Discord webhooks or a telegram bot._

--------------------------------------
```↓changes↓
◦ fixed a big heap of bugs
◦ reduced size
◦ improved performance
◦ improved code readability
◦ changed the sending methods
◦ changed uploading a file method
◦ changed the method of taking tokens
◦ most of the code has been completely rewritten
◦ complete change of basic functions
◦ improved detection protection
◦ improved tamper resistance
◦ and a lot of small changes and fixes
```

--------------------------------------

It doesn't have a builder yet, but can be easily assembled using the instructions in the readme

--------------------------------------
[source code](https://github.com/Nick-Vinesmoke/The-Murk-stealer/tree/master)

--------------------------------------

**Comment by Nick-Vinesmoke** [comment]
I fixed it

**Comment by Nick-Vinesmoke** [comment]
I hope so)
