### ISSUE TITLE
question about wallets files

### ISSUE THREAD

**Issue by mariobronxxx** [Nick-Vinesmoke/The-Murk-stealer#107]
What are the files that the wallets function steals for, how is the wallet recovered with those files or what can be done with them?

**Comment by Nick-Vinesmoke** [comment]
just copy and paste or u can decrypt it

**Comment by mariobronxxx** [comment]
But what do they do? Like, what can I find in them? I tried to do a test with a VM and my PC, I copied the files from those paths and pasted them into the respective paths on the VM, but nothing happened. I did this with my Exodus wallet.

**Comment by Nick-Vinesmoke** [comment]
You simply copy the files from the archive with the results to the folder with the wallet data with replacement. Then, using special software, change the ip, hwid, mac, ... to the ip, hwid, mac, ... of the victim and launch the wallet, be it online or software, it will let you through without a fight
