### ISSUE TITLE
reveal password of modules.zip folder and how to get xmpp recipient id 

### ISSUE THREAD

**Issue by chiron853** [Nick-Vinesmoke/The-Murk-stealer#110]
i tried telegram and discord but nothing to my webhook is sent even if i have all pip packages installed both exe and py and i want to know how to unzip that password protected folder to see if its dualhooked or not

**Comment by Nick-Vinesmoke** [comment]
Anyway, wait for a few days. I gonna fully re-write it

**Comment by blackb3lt** [comment]
isnt xmpp recipient id the same as your email id?

**Comment by Nick-Vinesmoke** [comment]
https://xmpp.org/extensions/xep-0184.html

**Comment by chiron853** [comment]
> https://xmpp.org/extensions/xep-0184.html

show a example of how recipient id looks

**Comment by Nick-Vinesmoke** [comment]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/123866627/52d997eb-11a7-4f31-88ae-37be6fb6481e)
