### ISSUE TITLE
It won't run?

### ISSUE THREAD

**Issue by CutyCat2000** [Nick-Vinesmoke/The-Murk-stealer#111]
When compiled with nuitka and taking it from the built folder, it wont run

**Comment by Nick-Vinesmoke** [comment]
wait for a few days. I gonna fully re-write it. And after that, everything should work properly.

**Comment by Nick-Vinesmoke** [comment]
**Meet the new version v9.3.0 of The Murk**
__🔐Powerful multi-platform stealer with a huge pack of grabbed data. Wallets stealer, browsers stealer, sessions stealer, etc. All logs will be sent using Discord webhooks or a telegram bot.__
--------------------------------------
```↓changes↓
◦ fixed a big heap of bugs
◦ reduced size
◦ improved performance
◦ improved code readability
◦ changed the sending methods
◦ changed uploading a file method
◦ changed the method of taking tokens
◦ most of the code has been completely rewritten
◦ complete change of basic functions
◦ improved detection protection
◦ improved tamper resistance
◦ and a lot of small changes and fixes
```
--------------------------------------
It doesn't have a builder yet, but can be easily assembled using the instructions in the readme
--------------------------------------
[source code](https://github.com/Nick-Vinesmoke/The-Murk-stealer/tree/master)
--------------------------------------

**Comment by Nick-Vinesmoke** [comment]
try it

**Comment by Poolj2023** [comment]
Bro, I consult you on Discord after 20 days it disables my account... is there any solution?

**Comment by Nick-Vinesmoke** [comment]
wdym

**Comment by Poolj2023** [comment]
When using your stealer on Discord it works fine, but after 20 days Discord disables my account.

**Comment by Poolj2023** [comment]
How can I contact you by telegram?

**Comment by Nick-Vinesmoke** [comment]
Our Discord server [join us](https://discord.gg/ufvyg5F2j4)

**Comment by Nick-Vinesmoke** [comment]
> When using your stealer on Discord it works fine, but after 20 days Discord disables my account.

join server
