### ISSUE TITLE
Bug with chromium type browsers cookies

### ISSUE THREAD

**Issue by mertcanaksoz** [Nick-Vinesmoke/The-Murk-stealer#113]
I have tested cookies on such browsers as Brave and Chrome, and I got nothing.

**Comment by Nick-Vinesmoke** [comment]
browsers constantly work with the file in which cookies are stored, so for cookies to be successfully taken, browsers must be closed

**Comment by Nick-Vinesmoke** [comment]
I can just close Chrome, especially since I’m going to write a new stealer in a normal language that will have many times more functionality, but in my free time I’ll try to bypass its protection

**Comment by Nick-Vinesmoke** [comment]
thx for ur advice

**Comment by Nick-Vinesmoke** [comment]
I guess I can just freeze a Chrome process

**Comment by Nick-Vinesmoke** [comment]
> > hrome, especially since I’m going to write a new stealer in a normal language that will have many times more functionality, but in my free time I’ll try to bypass its p
> 
> why would u want to do that?
> 
> better to get the data when chrome is open, it is kind a wierd when i open minecraft.exe and suddly chrome closes, wich is a indicator of infection

Bro, Idk how to do it. I tried many methods but even if chrome is frozen I can't copy it

**Comment by Nick-Vinesmoke** [comment]
> what methods u used? i used some trick and it works flawlessly, i can get it all when chrome is open

freezing proc, and duplicate

**Comment by Nick-Vinesmoke** [comment]
ok

**Comment by Nick-Vinesmoke** [comment]
Do you mean any of this
https://pypi.org/project/shadowcopy/
or
https://github.com/sblosser/pyshadowcopy

**Comment by Nick-Vinesmoke** [comment]
Oh, I found one method to do shadow copy and write one method but it needs administrative privileges

**Comment by Nick-Vinesmoke** [comment]
Thx I'll try

**Comment by Nick-Vinesmoke** [comment]
I did it https://github.com/Nick-Vinesmoke/The-Murk-stealer/commit/e4c8da36095856315eff5e547f28fd85cbefd5be
