### ISSUE TITLE
Chrome cookies

### ISSUE THREAD

**Issue by pizzpea1** [Nick-Vinesmoke/The-Murk-stealer#2]
When you run the code, you get a Cookies-Chrome.json in chrome folder. How do you import that folder into browser? It seems the format is not valid to most chrome extensions

**Comment by Nick-Vinesmoke** [comment]
You need to decrypt it!
[Example of decrypter](https://gist.github.com/DakuTree/428e5b737306937628f2944fbfdc4ffc)
[or this](https://stackoverflow.com/questions/60416350/chrome-80-how-to-decode-cookies)

**Comment by pizzpea1** [comment]
Okay, after decrypting it. How do I import it into chrome? The extensions I've tried say invalid format

**Comment by Nick-Vinesmoke** [comment]
maybe a little later I will add decryption to the stiller

**Comment by Nick-Vinesmoke** [comment]
[it should work](https://gologin.com/blog/cookie-import-export)

**Comment by Nick-Vinesmoke** [comment]
Yes

**Comment by Nick-Vinesmoke** [comment]
star pls)
![image](https://user-images.githubusercontent.com/123866627/226944038-cf2e3119-a872-4104-9542-b82e97d70a8d.png)

**Comment by Nick-Vinesmoke** [comment]
chrome cookies are stored in .bd files, and my stealer reads them and decrypts them into json. You can't just import other people's cookies into your chrome browser

**Comment by pizzpea1** [comment]
I can't just export my cookies? and import them back into my own browser? I definitely can do that, I figured it out yesterday. Chrome browser prevents it from happening because of obvious security vulnerabilities. I had to use a different browser, and it worked
