### ISSUE TITLE
heres a fully tested gpg file encryptor i made

### ISSUE THREAD

**Issue by FU3X** [Nick-Vinesmoke/The-Murk-stealer#22]
[main.py.txt](https://github.com/Nick-Vinesmoke/The-Murk-stealer/files/11194823/main.py.txt)

**Comment by FU3X** [comment]
maybe make a function for the pgp-key variable idk, but it explicitly needs to be pgpkey = r"""key"""

**Comment by Nick-Vinesmoke** [comment]
Ok, thx. Write it not to issue write it to [💡Ideas](https://github.com/Nick-Vinesmoke/The-Murk-stealer/discussions/categories/ideas)

**Comment by RiaxStuff** [comment]
hi again, pretty off-topic but is there a way to execute this without having all the libs?

Basically as one person said it's pretty hard to make it work. They need python + all the libs in order to execute the stub. If it was one .exe all packed (if possible) it would be way better.

Pretty cool tool tho, would be the best if it wasn't for the execution problems. 🌟

**Comment by Nick-Vinesmoke** [comment]
When you build a stealer you need to have all the libraries to build it. After assembly, there will be a fully equipped stealer and when the victim launches it, it will work regardless of whether she has those libraries or even Python

**Comment by FU3X** [comment]
> hi again, pretty off-topic but is there a way to execute this without having all the libs?
> 
> Basically as one person said it's pretty hard to make it work. They need python + all the libs in order to execute the stub. If it was one .exe all packed (if possible) it would be way better.
> 
> Pretty cool tool tho, would be the best if it wasn't for the execution problems. 🌟

🤦🤦

**Comment by RiaxStuff** [comment]
> When you build a stealer you need to have all the libraries to build it. After assembly, there will be a fully equipped stealer and when the victim launches it, it will work regardless of whether she has those libraries or even Python

I have built it but the stub (output exe) won't boot up without python. Maybe I'm using the wrong one? Like I don't know at this point lol.

**Comment by FU3X** [comment]
> > When you build a stealer you need to have all the libraries to build it. After assembly, there will be a fully equipped stealer and when the victim launches it, it will work regardless of whether she has those libraries or even Python
> 
> I have built it but the stub (output exe) won't boot up without python. Maybe I'm using the wrong one? Like I don't know at this point lol.

are you doing this in a vm or sandboxed environment

**Comment by RiaxStuff** [comment]
yeah

**Comment by FU3X** [comment]
> > > > When you build a stealer you need to have all the libraries to build it. After assembly, there will be a fully equipped stealer and when the victim launches it, it will work regardless of whether she has those libraries or even Python
> > > 
> > > 
> > > I have built it but the stub (output exe) won't boot up without python. Maybe I'm using the wrong one? Like I don't know at this point lol.
> > 
> > 
> > are you doing this in a vm or sandboxed environment
> 
> same built in normal environment and it works but only if u have python the exe in the root dir does not work but the one in the "forBuild" "this" works (only w/ python) i am prob retarded or something

you're using the builder right? and its compiling using Nuitka? or are you compiling manually

**Comment by Nick-Vinesmoke** [comment]
I'm so sorry

**Comment by Nick-Vinesmoke** [comment]
You got this error cause I tested only stealer not builder, sorry

**Comment by RiaxStuff** [comment]
Alright, please let me know once it's fixed.
Cheers and good luck!

**Comment by Nick-Vinesmoke** [comment]
⭐Please, star this repo if it was helpful⭐

**Comment by Nick-Vinesmoke** [comment]
thx, pls share my source stealer to help me get more stars, thx

**Comment by RiaxStuff** [comment]
I'm sorry but it isn't safe. 
I am unable to test it because I'm pretty positive that this is a virus after running it in sandboxie.

Someone can correct me if I am wrong but I doubt it.
