### ISSUE TITLE
Some functions

### ISSUE THREAD

**Issue by SMDXGitHub** [Nick-Vinesmoke/The-Murk-stealer#25]
yee it aint legit drops off 1.exe in your temp folder and sends data using python executions like are u for real bro.

**Comment by RiaxStuff** [comment]
you should have used it in a sandbox bypass env.

**Comment by Nick-Vinesmoke** [comment]
Sorry, I do this program in the team I wrote the code and my teammate test it and prepare it to release. I trust him but how I can see he is dumb. I'm so sorry I'll test his work. This is fully clean (https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v6.0.3)

**Comment by Nick-Vinesmoke** [comment]
I'm so sorry

**Comment by Nick-Vinesmoke** [comment]
> > I'm so sorry
> 
> sadly, no one will believe you now.
> 
> the executions were 100% intentional and obvious if you ask me. (python lib upon successful execution of the builder) that will pop on with "1" as its name in the temp folder. also it uses network so there you go ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
> 
> I am will still support your work but can't say the same for others.
> 
> And for those that got infected did u expect a fully safe builder?

There was a text spammer not more. He enters the computer and through Outlook spam all contacts once and so every time the program is started

**Comment by Nick-Vinesmoke** [comment]
I'll remove all releases with it, and close this topic when @SMDXGitHub see my reply

**Comment by SMDXGitHub** [comment]
cap dualhooked

**Comment by Nick-Vinesmoke** [comment]
> cap dualhooked

(
