### ISSUE TITLE
how to load steam

### ISSUE THREAD

**Issue by SMDXGitHub** [Nick-Vinesmoke/The-Murk-stealer#31]
it never works :(

**Comment by Nick-Vinesmoke** [comment]
what did you mean?

**Comment by Nick-Vinesmoke** [comment]
This is results of my laptop for work 
![image](https://user-images.githubusercontent.com/123866627/232100754-133accb2-5dce-4f72-b327-2dd191ac00b2.png)
![image](https://user-images.githubusercontent.com/123866627/232100800-3edf658a-1d8a-4b71-8643-ab5945e2dfe8.png)
steam successfully grabbed

**Comment by SMDXGitHub** [comment]
when i paste their files in my steam dir and hit replace it throws me back into the login page tested multiple times on working sessions

**Comment by Nick-Vinesmoke** [comment]
The same with most sites and programs

**Comment by SMDXGitHub** [comment]
oh, so if i put in their creds with the replaced files do i get to bypasses the phone verif. ?

**Comment by Nick-Vinesmoke** [comment]
> So you need to create a new session in system emulation with all victim's data and then do your deals

if you do like this, yes if the victim doesn't turn on mandatory SMS confirmation, before transfer of funds

**Comment by SMDXGitHub** [comment]
i barely know what system emu. is 
also uplay is no longer a thing its "ubisoft connect" now.

**Comment by Nick-Vinesmoke** [comment]
> i barely know what system emu. is also uplay is no longer a thing its "ubisoft connect" now.

ok I'll add It too

**Comment by Nick-Vinesmoke** [comment]
pls ⭐Please, star this repo if it was helpful⭐, cause I re-published this repo to delete all back doors in code, don't download the release wich published  letter then today

**Comment by Nick-Vinesmoke** [comment]
I hope, I help you
