### ISSUE TITLE
I found two fucking repos which look like your stealer but it's virus, pls do something with

### ISSUE THREAD

**Issue by Mega-Dev-Eloper** [Nick-Vinesmoke/The-Murk-stealer#32]
Report 
https://github.com/Fizz222/TheMurkStealer2
https://github.com/ztevayadp40ve/The-Murk-stealer-on-python

**Comment by FU3X** [comment]
shut the fuck up

**Comment by Anonimus-Fog** [comment]
Yea, I saw it too

**Comment by Nick-Vinesmoke** [comment]
Report pls

**Comment by Nick-Vinesmoke** [comment]
thx, all fake repos were deleted

**Comment by secre159** [comment]
whats the password for the module?

**Comment by Serverlog1** [comment]
How do I set up your virus manually if I want it to send results to my telegram.
Will I install python and what other modules should I install
