### ISSUE TITLE
ERROR BUILD USING NUITKA

### ISSUE THREAD

**Issue by aljawary** [Nick-Vinesmoke/The-Murk-stealer#48]
i got this error when trying to build the stub pls help!

**Screenshot**
![Screenshot_1](https://user-images.githubusercontent.com/43963987/233509977-a68646f3-8900-42d6-a774-da3984c63745.png)

**Comment by Nick-Vinesmoke** [comment]
what version of python do you use?

**Comment by Nick-Vinesmoke** [comment]
Try to re-install python, nuitka and all following imports. This error means that you do not have some file or python library

**Comment by Nick-Vinesmoke** [comment]
But firstly re-install nuitka

**Comment by Nick-Vinesmoke** [comment]
soon I am going to add building using pyinstaller too

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.0.1 try this
