### ISSUE TITLE
Add feture

### ISSUE THREAD

**Issue by m6hdix** [Nick-Vinesmoke/The-Murk-stealer#5]
Add Extension Wallet log

**Comment by Nick-Vinesmoke** [comment]
Did you mean to add steal crypto wallet data?

**Comment by Nick-Vinesmoke** [comment]
You can use this for crypto wallets(https://github.com/Nick-Vinesmoke/Heat_CLIPPER)

**Comment by Nick-Vinesmoke** [comment]
> Did you mean to add steal crypto wallet data?

If you mean this I'm working on it now

**Comment by Nick-Vinesmoke** [comment]
done
