### ISSUE TITLE
To fix the encoding error:

### ISSUE THREAD

**Issue by FU3X** [Nick-Vinesmoke/The-Murk-stealer#57]
Yes, there is an option to enable UTF-8 for worldwide language support on Windows 10. Here’s how you can do it:

Press Win+R and type intl.cpl to open the regional settings in Control Panel.
Click on the Administrative tab.
Click the Change system locale button.
Enable Beta: Use Unicode UTF-8 for worldwide language support.
[Reboot your computer ](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do)[1](https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do).
[This feature is still in beta as of this writing ](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window)[2](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window). Would you like more information on this topic?

**Comment by Nick-Vinesmoke** [comment]
Thx
