### ISSUE TITLE
The command "nuitka" couldnt be found

### ISSUE THREAD

**Issue by TheRat3000** [Nick-Vinesmoke/The-Murk-stealer#58]
![image](https://user-images.githubusercontent.com/132710563/236559583-53bb0d06-b22f-4dee-a577-6c52eb96169b.png)

**Comment by Nick-Vinesmoke** [comment]
pip install Nuitka

**Comment by TheRat3000** [comment]
![image](https://user-images.githubusercontent.com/132710563/236650740-a52e07ed-1343-4a38-92d9-f5dd931a0b41.png)

**Comment by TheRat3000** [comment]
![image](https://user-images.githubusercontent.com/132710563/236650755-11a83380-3444-4303-aa3a-ac087dcedee0.png)

**Comment by Nick-Vinesmoke** [comment]
> ![image](https://user-images.githubusercontent.com/132710563/236650755-11a83380-3444-4303-aa3a-ac087dcedee0.png)

Idk it doesn't see nuitka

**Comment by TheRat3000** [comment]
No Idea why? :/

**Comment by Nick-Vinesmoke** [comment]
Idk, re-install nuitka and python
