### ISSUE TITLE
It is still the same, can you ping me when its updated?

### ISSUE THREAD

**Issue by CutyCat2000** [Nick-Vinesmoke/The-Murk-stealer#59]

**Comment by CutyCat2000** [comment]
The compiled exe is just not doing anything

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.0.1

**Comment by Nick-Vinesmoke** [comment]
> The compiled exe is just not doing anything

I can help if you have discord

**Comment by CutyCat2000** [comment]
I do :) Anonymous2.0#1686

**Comment by Nick-Vinesmoke** [comment]
I'll try to help you

**Comment by Nick-Vinesmoke** [comment]
MB fixed))

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.1.0 new release with all bugs fixed
