### ISSUE TITLE
Stealer does not send the log

### ISSUE THREAD

**Issue by Squatch55** [Nick-Vinesmoke/The-Murk-stealer#62]
I somehow managed to build it, but when my client runs the payload, it doesn't send the log. So it does nothing.

**Comment by Squatch55** [comment]
You can add me if you want to help via discord Squatch#0524

**Comment by Nick-Vinesmoke** [comment]
Ok, I'll do it).

**Comment by Nick-Vinesmoke** [comment]
I fixed all and add pyinstaller
