### ISSUE TITLE
No Cookies

### ISSUE THREAD

**Issue by Proxy3200** [Nick-Vinesmoke/The-Murk-stealer#72]
Sir i tried your stealer on my own PC. It is good for as spyware. The thing is it sends everything files etc even browser information like downloads but it won't send password and cookies. Kindly check

**Comment by Nick-Vinesmoke** [comment]
Okay, I'll take a look at this bug, stay tuned for an update soon

**Comment by Nick-Vinesmoke** [comment]
Okay, I'll take a look at this bug, stay tuned for an update soon

**Comment by Nick-Vinesmoke** [comment]
You got the error `can only concatenate str (not "TypeError") to str`. Now I fixed it wait till release or download from the branch dev
