### ISSUE TITLE
More UD

### ISSUE THREAD

**Issue by MICHELE-001x** [Nick-Vinesmoke/The-Murk-stealer#75]
I really like this project but is there a way to make it less detectable by AVs?

**Comment by Nick-Vinesmoke** [comment]
This is [The Murk on vt](https://www.virustotal.com/gui/file/8272122a3426287647dee5ad760b258804eca91ccee11d047bf1ea1b3454a2fa?nocache=1) сrypted by my own сrypter. It's a close source, but mb soon I'll post it to GitHub

**Comment by Nick-Vinesmoke** [comment]
I need to fix my сrypter. It still isn't ready to see the world

**Comment by Nick-Vinesmoke** [comment]
😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 
😁 ⭐Please, star this repo if it was helpful⭐😁 
😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁 😁

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/VineShield

> This is [The Murk on vt](https://www.virustotal.com/gui/file/8272122a3426287647dee5ad760b258804eca91ccee11d047bf1ea1b3454a2fa?nocache=1) сrypted by my own сrypter. It's a close source, but mb soon I'll post it to GitHub
