### ISSUE TITLE
Sending files

### ISSUE THREAD

**Issue by bilalmahsud** [Nick-Vinesmoke/The-Murk-stealer#76]
I was testing the files that goes to anonymfile.com sometime get duplicated with other people i got someone data i did't anything harm just testing.

**Comment by Nick-Vinesmoke** [comment]
What do you mean, the links can't match, and even if they do, the archives are password protected

**Comment by bilalmahsud** [comment]
ye it happened i don't know the reason behind why it happened i think chance of happening to someone is really low

**Comment by Nick-Vinesmoke** [comment]
the archives are password protected
