### ISSUE TITLE
Wallet Issue

### ISSUE THREAD

**Issue by Proxy3200** [Nick-Vinesmoke/The-Murk-stealer#81]
Hey sir, the guy below was saying right there is a wallet issue. I have not tried other wallets but I have metamask wallet on my PC and when I run your stealer it doesn't grab my metamask wallet. I have metamask wallet extension in my Microsoft edge.  Rest everything works like a charm🎇

**Comment by Nick-Vinesmoke** [comment]
Sup bro, thx for the feedback. I'll add extensions soon. Star this repo pls! Have a nice day
