### ISSUE TITLE
Builder not working after update

### ISSUE THREAD

**Issue by Proxy3200** [Nick-Vinesmoke/The-Murk-stealer#88]
Hi Nick I am again in the line with issues lol. Btw after the update the builder is not working properly. I have downloaded the compiled version by you. I have tried building with both Nuitika and Pyinstaller. None of them work. Nuitika Shows error, Pyinstaller shows that the file specified is not found. Pyarmor never worked even in the previous versions it says python 3.11 is not compatible with Pyarmor. But in previous versions Nuitka and Pyinstaller were working now they also stopped working. Please look into the issue

**Comment by Proxy3200** [comment]
I downgraded the python to version 3.7 so that it can work with PyArmor. The pyarmor Building process started but no dist folder was created. See this screenshot.
[https://imgur.com/a/RtyIRem](url)
_Also other previous version build that I built stopped working. They started showing this error. Has something changed on your backend side._
[https://imgur.com/a/Ef2A14x](url)

**Comment by Nick-Vinesmoke** [comment]
Thx I'll fix it

**Comment by Nick-Vinesmoke** [comment]
I got it, Wait till fix

**Comment by Nick-Vinesmoke** [comment]
Bro, There was an error that exe created but did not move to the main dir. After the completion of the console compilation window, you need to wait another minute

**Comment by Nick-Vinesmoke** [comment]
Or I idk in my ps and VM all good

**Comment by Proxy3200** [comment]
Sorry Nick That was my fault I didn't wait for 2 minutes. After waiting for 2 minutes. It successfully built the executable file. 
But there are still Big Issues,
**Issue with The Murk 9.0.5**
When I ran the executable file It gave me this error. Psutil module not found. See the screenshot
https://imgur.com/a/qAKcBN3
I tried installing psutil module using _pip install psutil_ but it threw me error that visual c++ 14.0 is required. I already have visual c++. I saw a solution that I have to install visual studio code with C++ development kit. I installed it and now **Successfully able to install Psutil** using same above command. But even after installing psutil its still shows same error that psutil is required and I am unable to run the executable file.
(I have installed all modules during the start of the builder process when I typed n to install necessary required python files)

**Issue with The Murk 8.2.5**
Murk 8.2.5 was working good until recently it started throwing me this error and stopped working. It shows different error then above murk 9.0.5
https://imgur.com/a/FMLhvrR

**Comment by Nick-Vinesmoke** [comment]
Idk this is an error with your pc other users haven't issues

**Comment by Proxy3200** [comment]
Everything was working fine until recently. I haven't changed anything on my PC. How can it all stopped working suddenly ?. I am sending you the executable file I built. Can you try running it on your Sandbox or VM?
https://anonfiles.com/j0u8f42bza/TheMurk_exe

**Comment by Nick-Vinesmoke** [comment]
Yeah, it works, but I deleted the folder, so u didn't get anything
