### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Freedomqing** [Nick-Vinesmoke/The-Murk-stealer#91]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/139445315/b51f4a95-504d-4976-ae6b-d9dd89c7bef8)
How to solve this fatal mistake

**Comment by Proxy3200** [comment]
Similar thing happens with me. It is the problem with your PC. I sent the executable file to Nick and he says everything works. Check if something missing in your PC. I can not find what is missing.
![Fatal Error](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/130583428/bf08fa25-8b93-4f51-beaa-e23a9df2875d)

**Comment by Steffano198** [comment]
same here


> ![image](https://user-images.githubusercontent.com/139445315/253670741-b51f4a95-504d-4976-ae6b-d9dd89c7bef8.png) How to solve this fatal mistake

**Comment by Nick-Vinesmoke** [comment]
ur compiler is out of date. Just write it in cmd `pip install "pyinstaller>=5.13.2"`(last ver) or replace pyinstaller to any other compiler which u use

**Comment by Steffano198** [comment]
> ur compiler is out of date. Just write it in cmd `pip install "pyinstaller>=5.13.2"`(last ver) or replace pyinstaller to any other compiler which u use

its fixed, something with auto-exe, updates, adjuist path, and it works
