### ISSUE TITLE
Nothing happening 

### ISSUE THREAD

**Issue by dustinwho** [Nick-Vinesmoke/The-Murk-stealer#94]
So i used the builder and everything , created the telegram bot , but whenever i run the malware on the test machine , nothing happens, it just loads and i receive nothing through the telegram bot

**Comment by Nick-Vinesmoke** [comment]
Hi run .py file and show me the console output

**Comment by Nick-Vinesmoke** [comment]
fixed, try the new [release](https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v9.2.0)
