### ISSUE TITLE
Writing to PC_info.txt error(system_info.py; line 238)

### ISSUE THREAD

**Issue by Hoangdepzaivcl** [Nick-Vinesmoke/The-Murk-stealer#98]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/124053344/1714d868-104e-4175-a513-c58d2646104a)

**Comment by Nick-Vinesmoke** [comment]
when did you get this error?

**Comment by Hoangdepzaivcl** [comment]
today

**Comment by Nick-Vinesmoke** [comment]
ok, how  did you get this error?

**Comment by Nick-Vinesmoke** [comment]
https://github.com/Nick-Vinesmoke/The-Murk-stealer/releases/tag/The_Murk_v9.2.7
fixed

**Comment by Nick-Vinesmoke** [comment]
**Meet the new version v9.3.0 of The Murk**
_🔐Powerful multi-platform stealer with a huge pack of grabbed data. Wallets stealer, browsers stealer, sessions stealer, etc. All logs will be sent using Discord webhooks or a telegram bot._

--------------------------------------
```↓changes↓
◦ fixed a big heap of bugs
◦ reduced size
◦ improved performance
◦ improved code readability
◦ changed the sending methods
◦ changed uploading a file method
◦ changed the method of taking tokens
◦ most of the code has been completely rewritten
◦ complete change of basic functions
◦ improved detection protection
◦ improved tamper resistance
◦ and a lot of small changes and fixes
```

--------------------------------------

It doesn't have a builder yet, but can be easily assembled using the instructions in the readme

--------------------------------------
[source code](https://github.com/Nick-Vinesmoke/The-Murk-stealer/tree/master)

--------------------------------------

**Comment by Nick-Vinesmoke** [comment]
try it
