### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by IneedGkk** [Nick-Vinesmoke/The-Murk-stealer#99]
please tell me how to get rid of this error sir 
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/87073662/02853e18-35dd-4a3e-b277-ad1e23b3e09d)

**Comment by IneedGkk** [comment]
![image](https://github.com/Nick-Vinesmoke/The-Murk-stealer/assets/87073662/184fb954-9aa3-4e97-9152-6d44510b0a91)

**Comment by Nick-Vinesmoke** [comment]
try to use another building method, and read [it](https://www.stechies.com/pip-not-recognized-internal-external-command/)

**Comment by IneedGkk** [comment]
all method are like this
